CREATE DATABASE empresa123 CHARACTER SET UTF8;

USE empresa123;

CREATE TABLE empleado(
NIF VARCHAR(9) NOT NULL,
nombre VARCHAR(45) NOT NULL,
apellido VARCHAR(45) NOT NULL,
administrador BOOL NOT NULL,
contraseña VARCHAR(20),
PRIMARY KEY (NIF));

CREATE TABLE fichaje(
id INT NOT NULL AUTO_INCREMENT,
NIF VARCHAR(9) NOT NULL,
fecha DATETIME,
fichajeEntrada TIME,
fichajeSalida TIME,
finalizado BOOL NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(NIF) REFERENCES empleado(NIF) ON DELETE CASCADE);

INSERT INTO empleado VALUES ("11111111H","Juan","Marqués",TRUE,"1dam");